# environment.yml
#
# Developmental synapse remodeling toolbox
# © Christoph Kirst
# https://github.com/ChristophKirst/developmental_syanpse_dynamics
#
# Licensed under GNU General Public License v3.0
#
# conda environment
#
# install: conda env create -f environment.yml
# update:  conda env update -f environment.yml

name: developmental_synapse_remodeling

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - ipython
  - numpy
  - scipy
  - matplotlib
  - tqdm
